name: exercise
description: "A test task"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  awesome_dio_interceptor: 1.2.0
  cupertino_icons: 1.0.6
  dio: 5.4.2+1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.5.1
  flutter_screenutil: 5.9.0
  flutter_svg: 2.0.10+1
  freezed_annotation: 2.4.1
  get_it: 7.6.8
  injectable: 2.4.1
  intl: 0.18.1
  json_annotation: 4.8.1
  retrofit: 4.1.0
  flutter_app_environment: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.9
  flutter_lints: 3.0.1
  freezed: 2.5.1
  hive_generator: 2.0.1
  injectable_generator: 2.6.1
  json_serializable: 6.7.1
  mockito: 5.4.4
  retrofit_generator: 8.1.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - res/assets/
    - res/config/
